### PR TITLE
Create dependabot.yml

### LINKED ISSUE #1387: [FEAT]: Add dependabot.yml to automatically detect and update dependencies
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Windows 11 23H2 Build 22631.2861

### Device

Legion 5 Pro 16ARX8

### Is your feature request related to a problem?

No problems to be reported, just a mere suggestion for automatism and to improve the project maintainability

### How would you like the problem to be solved?

DotNet dependencies (declared in the csproj file) used by the application can become outdated very easily. Same happens to the dependencies used in the repository actions. Using a dependabot.yml, which is completely supported by Github, will help to effortlesly detect the new versions and update them with automatic pull requests.

Additionally, with some little tweaks and another Github action, it is possible to automatically merge those pull requests to keep the project always updated.

### What alternatives have you considered?

Just the dependabot file, nothing else

### Additional information

I will open a pull requests with the changes suggested.

### PR DESCRIPTION
**Pull request by YisusChrist**
Closes #1387.

This will automatically open pull requests with dependencies updated detected on:
- [LenovoLegionToolkit.Lib.csproj](https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/master/LenovoLegionToolkit.Lib/LenovoLegionToolkit.Lib.csproj) file
- [.github/workflows](https://github.com/BartoszCichecki/LenovoLegionToolkit/tree/master/.github/workflows) folder

Just tested in my forked repository and I got pull requests like these ones:

image

# Recommended steps

Under [/settings/actions](https://github.com/BartoszCichecki/LenovoLegionToolkit/settings/actions) navigate to the section **Workflow permissions** and enable the option _Allow GitHub Actions to create and approve pull requests_:

image

### CODE REVIEW

**Comment by YisusChrist** [comment]
As mentioned in #1387, in order to setup an action to Automatically merge the Dependabot pull requests, you can follow this guide: https://jhale.dev/posts/auto-merging-prs

**Comment by YisusChrist** [comment]
Also sorry for the garbage in the commits history, I was messing with the actions and I didn't want those changes to be applied to the project.

**Comment by BartoszCichecki** [comment]
No worries and sorry for late reply. How can we configure updates so that:

1. some can be excluded - I want to exclude WPFUI since it's a large migration
2. some can be set to update to beta versions - cswin32 is still in beta

**Comment by BartoszCichecki** [comment]
I will close this PR. I appreciate the input and in general agree with the concept. However, now that there aren't so many updates for LLT happening this isn't a big deal.

**Pull request closed without merging**
