### PR TITLE
Match system accent color & minor fixes

### PR DESCRIPTION
**Pull request by mariobalanica**
This adds the option to match both the app accent color and/or keyboard lightning zones to the system color.

### CODE REVIEW

**Comment by BartoszCichecki** [comment]
Hey, thanks for great PR! Also cool idea with syncing the keyboard lightning.

I will do my best to review and merge this next week as upcoming days are pretty full.

**Comment by BartoszCichecki** [comment]
I was a little bit too quick with merging this one and had to revert it, since I found couple of problems.

**First issue:**
The main problem is that it seems that checking the checkbox to follow system accent, messes up the color structure.

Steps to reproduce:
1. Set the accent color to something very different from you windows accent i.e. pure red
2. Check the "follow system accent" checkbox
3. Restart LLT
4. Go uncheck the checkbox.

Result:
LLT does not go back to the original color that was set before nor it stays on system accent color. When unchecking the check box I think it could be ok to not remember the previous color set by user, but it's not ok when it ends up in a weird state like described. It seems that for some reason it messes up the R component in the color struct. What is more the color box does not always follow the selected color anymore.

**Second issue:**
When switching the profiles, the color indicator boxes are not always show when needed.

Steps to reproduce:
1. Set Profile 1 to Static color and sync all zones to with system.
2. Change to "Off" profile.
3. Change back to Profile 1.
4. Color indicators next to zones do not appear.

I never really assumed that there would be a feature like this comming, so likely more changes, are needed, looking at the code, especially to Color card controls which seem to be the main issue and are becoming kind of spaghetti.

This isn't super high priority to be honest. Please let me know if you want to continue working on this or not.

**Comment by mariobalanica** [comment]
Hi, I was able to reproduce both issues and will try to look into them this week.

>I never really assumed that there would be a feature like this comming, so likely more changes, are needed, looking at the code, especially to Color card controls which seem to be the main issue and are becoming kind of spaghetti.

Can you tell me what do you think should be changed in the color card control?

**Comment by BartoszCichecki** [comment]
That's a good question, but it gets kind of messy with all the calls to `SetColor` and events it produces, that part should be cleaned up.

I am also thinking that the `ThemeManager` should be the source of truth, so maybe we need an interface `IThemeManager` and an `AbstractThemeManager` in the Lib part. The abstract one would contain what you placed in the `ThemeListener` and then the `ThemeManager` would extend abstract with all the current `Wpf.Ui` related stuff.

**Comment by mariobalanica** [comment]
> That's a good question, but it gets kind of messy with all the calls to SetColor and events it produces, that part should be cleaned up.

Yeah, I was thinking the same.

> I am also thinking that the ThemeManager should be the source of truth, so maybe we need an interface IThemeManager and an AbstractThemeManager in the Lib part. The abstract one would contain what you placed in the ThemeListener and then the ThemeManager would extend abstract with all the current Wpf.Ui related stuff.

Actually it seems that Wpf.Ui can handle system theme / accent changes on its own, so we can drop the dark mode listening code, rename `SystemThemeListener` to `SystemAccentListener` and keep using it only in the `RGBKeyboardBacklightController` and `ColorCardSystemAwareControl`, since these need to be independent of the UI preferences. What do you think?

**Comment by BartoszCichecki** [comment]
Wpf.Ui had some isues in previous releases, but I think it's worth trying now! Good idea.

**Comment by lenuswalker** [comment]
Anything happening on this one?

**Comment by mariobalanica** [comment]
Yes, I'll submit another PR soon.

**Comment by younyokel** [comment]
Is there any progress on this? Still no system accent color.

**Comment by BartoszCichecki** [comment]
Not really, there are other things that have much higher priority.

**Comment by mariobalanica** [comment]
The app accent part is done but my plans for keyboard lightning have changed a bit and I didn't have much time to work on it.

I'll probably submit the first part and finish the rest later.

**Pull request merged**
