### PR TITLE
Spectrum Support

### PR DESCRIPTION
**Pull request by BartoszCichecki**

### CODE REVIEW

**Comment by InvaderDolan** [comment]
Is this possible to adapt Spectrum to older Legion's? Such as 2021 models which have Corsair bloatware. I have 16ACHg6 and can test it if needed.

**Comment by BartoszCichecki** [comment]
> Is this possible to adapt Spectrum to older Legion's? Such as 2021 models which have Corsair bloatware. I have 16ACHg6 and can test it if needed.

No, it's not possible.

**Comment by InvaderDolan** [comment]
> > Is this possible to adapt Spectrum to older Legion's? Such as 2021 models which have Corsair bloatware. I have 16ACHg6 and can test it if needed.
> 
> No, it's not possible.

Why? Is hardware that different of some proprietary controllers on the way? Just wondering what's the reason, if you don't mind.

**Comment by BartoszCichecki** [comment]
Yes, iCue uses a whole different controller and protocol for RGB and since it was ever used only on two models and will not be used again it seems, it is not worth the time to reverse engineer, implement and test it.

**Comment by InvaderDolan** [comment]
> Yes, iCue uses a whole different controller and protocol for RGB and since it was ever used only on two models and will not be used again it seems, it is not worth the time to reverse engineer, implement and test it.

Thank you for answer. I hope, there will be some mad lad who will do this and share it with you to implement it into the program :)

**Comment by BartoszCichecki** [comment]
Well, OpenRGB supports iCue, so you have an alternative.

**Comment by BartoszCichecki** [comment]
No that is not planned.

**Comment by InvaderDolan** [comment]
> No that is not planned.

Too much effort for small exhaust, I get it.

**Pull request merged**
